### PR TITLE
Combined dependencies PR

### PR DESCRIPTION
**Pull request by iwahbe**
Combining multiple dependencies PRs into one.

<details>
<summary>Instructions for merging</summary>

* **Use a merge commit**, so that GitHub will mark all original PRs as merged.
* If your repository does not have merge commits enabled, please temporarily enable them in settings. Tick `Allow merge commits` in the repository settings.
* When ready, merge this PR using `Create a merge commit`.

</details>

## Combined PRs

* Bump golang.org/x/text from 0.3.3 to 0.3.8 in /azuresphere (#24) @app/dependabot
* Bump golang.org/x/crypto from 0.0.0-20200622213623-75b288015ac9 to 0.1.0 in /azuresphere (#23) @app/dependabot
* Bump golang.org/x/net from 0.0.0-20201021035429-f5854403a974 to 0.7.0 in /providerhub (#21) @app/dependabot
* Bump golang.org/x/net from 0.0.0-20201021035429-f5854403a974 to 0.7.0 in /powerbidedicated (#20) @app/dependabot
* Bump golang.org/x/net from 0.0.0-20201021035429-f5854403a974 to 0.7.0 in /peering (#19) @app/dependabot
* Bump golang.org/x/net from 0.0.0-20201021035429-f5854403a974 to 0.7.0 in /policyinsights (#18) @app/dependabot
* Bump golang.org/x/net from 0.0.0-20201021035429-f5854403a974 to 0.7.0 in /powerbi (#17) @app/dependabot
* Bump golang.org/x/net from 0.0.0-20201021035429-f5854403a974 to 0.7.0 in /powerplatform (#15) @app/dependabot
* Bump golang.org/x/net from 0.0.0-20201021035429-f5854403a974 to 0.7.0 in /purview (#16) @app/dependabot
* Bump golang.org/x/net from 0.0.0-20201021035429-f5854403a974 to 0.7.0 in /portal (#14) @app/dependabot
* Bump golang.org/x/text from 0.3.3 to 0.3.8 in /purview (#13) @app/dependabot
* Bump golang.org/x/crypto from 0.0.0-20200622213623-75b288015ac9 to 0.1.0 in /quantum (#11) @app/dependabot
* Bump golang.org/x/text from 0.3.3 to 0.3.8 in /quantum (#10) @app/dependabot

### CODE REVIEW

**Review by t0yv0 — APPROVED** [review]
🚢

**Review by mikhailshilkov — CHANGES_REQUESTED** [review]
This repo is auto-generated from `pulumi/azure-native`. I don't think we can do upgrades manually.

**Comment by iwahbe** [comment]
@mikhailshilkov can we disable @dependabot on it then?

**Comment by mikhailshilkov** [comment]
It looks like it's disabled now

**Pull request closed without merging**
